{
 "title": "AWS Health Status",
 "description": "Dashboard for aws-health-exporter.",
 "tags": [
  "aws",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "region", "label": "Region", "query": "label_values(region)" }
  ]
 },
 "panels": [
  {
   "title": "Currently Open Scheduled Changes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aws_health_events{category=\"scheduledChanges\",status_code=\"open\",region=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Currently Open Issues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aws_health_events{category=\"issue\",status_code=\"open\",region=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Currently Open Account Notifications",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aws_health_events{category=\"accountNotification\",status_code=\"open\",region=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Current Open Issues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "aws_health_events{category=\"issue\",status_code=\"open\",region=~\"$region\"}",
     "legendFormat": "{{ region }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Recently Closed Issues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "aws_health_events{category=\"issue\",status_code=\"closed\",region=~\"$region\"}",
     "legendFormat": "{{ region }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Upcomming Account Notifications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "aws_health_events{category=\"accountNotification\",status_code=\"upcoming\",region=~\"$region\"}",
     "legendFormat": "{{ region }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Current Open Account Notifications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "aws_health_events{category=\"accountNotification\",status_code=\"open\",region=~\"$region\"}",
     "legendFormat": "{{ region }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Recently Closed Account Notifications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "aws_health_events{category=\"accountNotification\",status_code=\"closed\",region=~\"$region\"}",
     "legendFormat": "{{ region }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Upcoming Scheduled Changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "aws_health_events{category=\"scheduledChange\",status_code=\"upcoming\",region=~\"$region\"}",
     "legendFormat": "{{ region }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Upcoming Scheduled Changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "aws_health_events{category=\"scheduledChange\",status_code=\"upcoming\",region=~\"$region\"}",
     "legendFormat": "{{ region }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Recently Closed Scheduled Changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "aws_health_events{category=\"scheduledChanges\",status_code=\"closed\",region=~\"$region\"}",
     "legendFormat": "{{ region }} - {{ service }}"
    }
   ]
  }
 ]
}